@extends('components.admin')
@section('title', 'Jenis Pelanggaran')
@section('content')
<div class="py-8 space-y-6">
    <div><h1 class="text-3xl font-bold">Jenis Pelanggaran</h1><p class="text-slate-500">Kelola kategori dan bobot skor pelanggaran.</p></div>
    @if(session('success'))<div class="p-4 bg-emerald-50 text-emerald-700 rounded-xl">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="p-4 bg-red-50 text-red-700 rounded-xl">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="p-4 bg-red-50 text-red-700 rounded-xl">{{ $errors->first() }}</div>@endif
    <section class="bg-white rounded-2xl border shadow-sm p-6"><form method="POST" action="{{ route('admin.pelanggaran.store') }}" class="grid grid-cols-1 md:grid-cols-4 gap-4">@csrf<select name="kategori" required class="border rounded-xl px-4 py-3"><option value="">Kategori</option><option value="ringan">Ringan</option><option value="sedang">Sedang</option><option value="berat">Berat</option></select><input name="deskripsi" required class="border rounded-xl px-4 py-3 md:col-span-2" placeholder="Deskripsi pelanggaran"><input type="number" min="1" name="skor" required class="border rounded-xl px-4 py-3" placeholder="Skor"><button class="md:col-span-4 bg-blue-700 text-white rounded-xl py-3">Tambah Jenis Pelanggaran</button></form></section>
    <section class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Kategori</th><th class="p-4 text-left">Deskripsi</th><th class="p-4 text-left">Skor</th><th class="p-4 text-center">Aksi</th></tr></thead><tbody>
        @forelse($pelanggarans as $item)<tr class="border-t"><td class="p-4 capitalize">{{ $item->kategori }}</td><td class="p-4">{{ $item->deskripsi }}</td><td class="p-4 font-semibold">{{ $item->skor }}</td><td class="p-4"><div class="flex justify-center gap-3" x-data="{edit:false}"><button type="button" @click="edit=true" class="text-blue-700">Edit</button><form method="POST" action="{{ route('admin.pelanggaran.delete',$item) }}" onsubmit="return confirm('Hapus jenis pelanggaran?')">@csrf @method('DELETE')<button class="text-red-600">Hapus</button></form><div x-show="edit" x-cloak class="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-4"><form @click.outside="edit=false" method="POST" action="{{ route('admin.pelanggaran.update',$item) }}" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl text-left">@csrf @method('PUT')<h3 class="font-semibold text-lg mb-4">Edit Jenis Pelanggaran</h3><div class="space-y-4"><select name="kategori" required class="w-full border rounded-xl px-4 py-3"><option value="ringan" @selected($item->kategori==='ringan')>Ringan</option><option value="sedang" @selected($item->kategori==='sedang')>Sedang</option><option value="berat" @selected($item->kategori==='berat')>Berat</option></select><input name="deskripsi" value="{{ $item->deskripsi }}" required class="w-full border rounded-xl px-4 py-3"><input type="number" min="1" name="skor" value="{{ $item->skor }}" required class="w-full border rounded-xl px-4 py-3"><p class="text-xs text-slate-500">Perubahan skor master tidak mengubah skor riwayat skorsing lama.</p><button class="w-full bg-blue-700 text-white rounded-xl py-3">Simpan</button></div></form></div></div></td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Belum ada data.</td></tr>@endforelse
        </tbody></table></div><div class="p-4">{{ $pelanggarans->links() }}</div></section>
</div>
@endsection
